In [1]:
import kagglehub
import pandas as pd
# Download latest version
path = kagglehub.dataset_download("yeanzc/telco-customer-churn-ibm-dataset")

pd.options.display.max_info_columns=100

pd.set_option('display.max_columns', None)


df = pd.read_excel(f"{path}/Telco_customer_churn.xlsx")
df.describe()

/home/oskar/Desktop/ChurnTeleco/venv/lib/python3.14/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

,Count,Zip Code,Latitude,Longitude,Tenure Months,Monthly Charges,Churn Value,Churn Score,CLTV
count,7043.0,7043.000000,7043.000000,7043.000000,7043.000000,7043.000000,7043.000000,7043.000000,7043.000000
mean,1.0,93521.964646,36.282441,-119.798880,32.371149,64.761692,0.265370,58.699418,4400.295755
std,0.0,1865.794555,2.455723,2.157889,24.559481,30.090047,0.441561,21.525131,1183.057152
min,1.0,90001.000000,32.555828,-124.301372,0.000000,18.250000,0.000000,5.000000,2003.000000
25%,1.0,92102.000000,34.030915,-121.815412,9.000000,35.500000,0.000000,40.000000,3469.000000
50%,1.0,93552.000000,36.391777,-119.730885,29.000000,70.350000,0.000000,61.000000,4527.000000
75%,1.0,95351.000000,38.224869,-118.043237,55.000000,89.850000,1.000000,75.000000,5380.500000
max,1.0,96161.000000,41.962127,-114.192901,72.000000,118.750000,1.000000,100.000000,6500.000000

In [2]:
info_custom = pd.DataFrame({
    'Columna': df.columns,
    'DType': df.dtypes,
    'Valores no nulos': df.notna().sum(),
    'Valores nulos': df.isna().sum()
}).reset_index(drop=True)

info_custom

              Columna    DType  Valores no nulos  Valores nulos
0          CustomerID      str              7043              0
1               Count    int64              7043              0
2             Country      str              7043              0
3               State      str              7043              0
4                City      str              7043              0
5            Zip Code    int64              7043              0
6            Lat Long      str              7043              0
7            Latitude  float64              7043              0
8           Longitude  float64              7043              0
9              Gender      str              7043              0
10     Senior Citizen      str              7043              0
11            Partner      str              7043              0
12         Dependents      str              7043              0
13      Tenure Months    int64              7043              0
14      Phone Service      str              7043              0
15     Multiple Lines      str              7043              0
16   Internet Service      str              7043              0
17    Online Security      str              7043              0
18      Online Backup      str              7043              0
19  Device Protection      str              7043              0
20       Tech Support      str              7043              0
21       Streaming TV      str              7043              0
22   Streaming Movies      str              7043              0
23           Contract      str              7043              0
24  Paperless Billing      str              7043              0
25     Payment Method      str              7043              0
26    Monthly Charges  float64              7043              0
27      Total Charges   object              7043              0
28        Churn Label      str              7043              0
29        Churn Value    int64              7043              0
30        Churn Score    int64              7043              0
31               CLTV    int64              7043              0
32       Churn Reason      str              1869           5174

In [3]:
from sqlalchemy import create_engine
import os
import numpy as np
import seaborn as sns
from dotenv import load_dotenv

load_dotenv()

DB_USER=os.getenv("DB_USER")
DB_PASS=os.getenv("DB_PASS")
DB_HOST=os.getenv("DB_HOST", "localhost")
DB_PORT=os.getenv("DB_PORT", "5432")
DB_NAME=os.getenv("DB_NAME", "churnteleco")


df.columns= df.columns.str.lower().str.replace(' ', '_')

url_sql = f'postgresql://{DB_USER}:{DB_PASS}@{DB_HOST}:{DB_PORT}/{DB_NAME}'

engine = create_engine(url_sql)

df.to_sql('customers_raw', engine, schema='raw', if_exists='append', index=False)

113

In [4]:
query_full = 'SELECT * FROM staging.costumers;'

df= pd.read_sql(query_full, engine)

print(df)

     costumer_id  count_costumer        country state_costumer          city  \
0     3668-QPYBK               1  United States     California   Los Angeles
1     9237-HQITU               1  United States     California   Los Angeles
2     9305-CDSKC               1  United States     California   Los Angeles
3     7892-POOKP               1  United States     California   Los Angeles
4     0280-XJGEX               1  United States     California   Los Angeles
...          ...             ...            ...            ...           ...
7038  2569-WGERO               1  United States     California       Landers
7039  6840-RESVB               1  United States     California      Adelanto
7040  2234-XADUH               1  United States     California         Amboy
7041  4801-JZAZL               1  United States     California  Angelus Oaks
7042  3186-AJIEK               1  United States     California  Apple Valley

     zip_code                lat_long   latitude   longitude  gender  \
0       90003  33.964131, -118.272783  33.964131 -118.272783    Male
1       90005   34.059281, -118.30742  34.059281 -118.307420  Female
2       90006  34.048013, -118.293953  34.048013 -118.293953  Female
3       90010  34.062125, -118.315709  34.062125 -118.315709  Female
4       90015  34.039224, -118.266293  34.039224 -118.266293    Male
...       ...                     ...        ...         ...     ...
7038    92285  34.341737, -116.539416  34.341737 -116.539416  Female
7039    92301  34.667815, -117.536183  34.667815 -117.536183    Male
7040    92304  34.559882, -115.637164  34.559882 -115.637164  Female
7041    92305     34.1678, -116.86433  34.167800 -116.864330  Female
7042    92308  34.424926, -117.184503  34.424926 -117.184503    Male

     senior_citizen patner dependents  tenure_months phone_service  \
0                No     No         No              2           Yes
1                No     No        Yes              2           Yes
2                No     No        Yes              8           Yes
3                No    Yes        Yes             28           Yes
4                No     No        Yes             49           Yes
...             ...    ...        ...            ...           ...
7038             No     No         No             72           Yes
7039             No    Yes        Yes             24           Yes
7040             No    Yes        Yes             72           Yes
7041             No    Yes        Yes             11            No
7042             No     No         No             66           Yes

        multiple_lines internet_service      online_security  \
0                   No              DSL                  Yes
1                   No      Fiber optic                   No
2                  Yes      Fiber optic                   No
3                  Yes      Fiber optic                   No
4                  Yes      Fiber optic                   No
...                ...              ...                  ...
7038                No               No  No internet service
7039               Yes              DSL                  Yes
7040               Yes      Fiber optic                   No
7041  No phone service              DSL                  Yes
7042                No      Fiber optic                  Yes

            online_backup    device_protection         tech_support  \
0                     Yes                   No                   No
1                      No                   No                   No
2                      No                  Yes                   No
3                      No                  Yes                  Yes
4                     Yes                  Yes                   No
...                   ...                  ...                  ...
7038  No internet service  No internet service  No internet service
7039                   No                  Yes                  Yes
7040                  Yes                  Yes                   No
7041                   No                   No                   No
7042                   No                  Yes                  Yes

             streaming_tv     streaming_movies        contract  \
0                      No                   No  Month-to-month
1                      No                   No  Month-to-month
2                     Yes                  Yes  Month-to-month
3                     Yes                  Yes  Month-to-month
4                     Yes                  Yes  Month-to-month
...                   ...                  ...             ...
7038  No internet service  No internet service        Two year
7039                  Yes                  Yes        One year
7040                  Yes                  Yes        One year
7041                   No                   No  Month-to-month
7042                  Yes                  Yes        Two year

     paperless_billing             payment_method  monthly_charge  \
0                  Yes               Mailed check           53.85
1                  Yes           Electronic check           70.70
2                  Yes           Electronic check           99.65
3                  Yes           Electronic check          104.80
4                  Yes  Bank transfer (automatic)          103.70
...                ...                        ...             ...
7038               Yes  Bank transfer (automatic)           21.15
7039               Yes               Mailed check           84.80
7040               Yes    Credit card (automatic)          103.20
7041               Yes           Electronic check           29.60
7042               Yes  Bank transfer (automatic)          105.65

      total_charges churn_label  churn_value  churn_score  cltv  \
0            108.15         Yes            1           86  3239
1            151.65         Yes            1           67  2701
2            820.50         Yes            1           86  5372
3           3046.05         Yes            1           84  5003
4           5036.30         Yes            1           89  5340
...             ...         ...          ...          ...   ...
7038        1419.40          No            0           45  5306
7039        1990.50          No            0           59  2140
7040        7362.90          No            0           71  5560
7041         346.45          No            0           59  2793
7042        6844.50          No            0           38  5097

                       churn_reason
0      Competitor made better offer
1                             Moved
2                             Moved
3                             Moved
4     Competitor had better devices
...                             ...
7038                            NaN
7039                            NaN
7040                            NaN
7041                            NaN
7042                            NaN

[7043 rows x 33 columns]

# Reconocimiento:

Cuantas filas tiene la tabla, y que forma tiene:

In [18]:
query_filas = "SELECT COUNT(*) FROM staging.costumers;"

df = pd.read_sql(query_filas, engine)

print(df)

   count
0   7043

In [19]:
query_base = "SELECT * FROM staging.costumers LIMIT 10;"

df= pd.read_sql(query_base, engine)

print(df)

  costumer_id  count_costumer        country state_costumer         city  \
0  3668-QPYBK               1  United States     California  Los Angeles
1  9237-HQITU               1  United States     California  Los Angeles
2  9305-CDSKC               1  United States     California  Los Angeles
3  7892-POOKP               1  United States     California  Los Angeles
4  0280-XJGEX               1  United States     California  Los Angeles
5  4190-MFLUW               1  United States     California  Los Angeles
6  8779-QRDMV               1  United States     California  Los Angeles
7  1066-JKSGK               1  United States     California  Los Angeles
8  6467-CHFZW               1  United States     California  Los Angeles
9  8665-UTDHZ               1  United States     California  Los Angeles

  zip_code                lat_long   latitude   longitude  gender  \
0    90003  33.964131, -118.272783  33.964131 -118.272783    Male
1    90005   34.059281, -118.30742  34.059281 -118.307420  Female
2    90006  34.048013, -118.293953  34.048013 -118.293953  Female
3    90010  34.062125, -118.315709  34.062125 -118.315709  Female
4    90015  34.039224, -118.266293  34.039224 -118.266293    Male
5    90020  34.066367, -118.309868  34.066367 -118.309868  Female
6    90022   34.02381, -118.156582  34.023810 -118.156582    Male
7    90024  34.066303, -118.435479  34.066303 -118.435479    Male
8    90028  34.099869, -118.326843  34.099869 -118.326843    Male
9    90029  34.089953, -118.294824  34.089953 -118.294824    Male

  senior_citizen patner dependents  tenure_months phone_service  \
0             No     No         No              2           Yes
1             No     No        Yes              2           Yes
2             No     No        Yes              8           Yes
3             No    Yes        Yes             28           Yes
4             No     No        Yes             49           Yes
5             No    Yes         No             10           Yes
6            Yes     No         No              1            No
7             No     No         No              1           Yes
8             No    Yes        Yes             47           Yes
9             No    Yes         No              1            No

     multiple_lines internet_service      online_security  \
0                No              DSL                  Yes
1                No      Fiber optic                   No
2               Yes      Fiber optic                   No
3               Yes      Fiber optic                   No
4               Yes      Fiber optic                   No
5                No              DSL                   No
6  No phone service              DSL                   No
7                No               No  No internet service
8               Yes      Fiber optic                   No
9  No phone service              DSL                   No

         online_backup    device_protection         tech_support  \
0                  Yes                   No                   No
1                   No                   No                   No
2                   No                  Yes                   No
3                   No                  Yes                  Yes
4                  Yes                  Yes                   No
5                   No                  Yes                  Yes
6                   No                  Yes                   No
7  No internet service  No internet service  No internet service
8                  Yes                   No                   No
9                  Yes                   No                   No

          streaming_tv     streaming_movies        contract paperless_billing  \
0                   No                   No  Month-to-month               Yes
1                   No                   No  Month-to-month               Yes
2                  Yes                  Yes  Month-to-month               Yes
3                  Yes                  Yes  Month-to-month               Yes
4                  Yes                  Yes  Month-to-month               Yes
5                   No                   No  Month-to-month                No
6                   No                  Yes  Month-to-month               Yes
7  No internet service  No internet service  Month-to-month                No
8                  Yes                  Yes  Month-to-month               Yes
9                   No                   No  Month-to-month                No

              payment_method  monthly_charge  total_charges churn_label  \
0               Mailed check           53.85         108.15         Yes
1           Electronic check           70.70         151.65         Yes
2           Electronic check           99.65         820.50         Yes
3           Electronic check          104.80        3046.05         Yes
4  Bank transfer (automatic)          103.70        5036.30         Yes
5    Credit card (automatic)           55.20         528.35         Yes
6           Electronic check           39.65          39.65         Yes
7               Mailed check           20.15          20.15         Yes
8           Electronic check           99.35        4749.15         Yes
9           Electronic check           30.20          30.20         Yes

   churn_value  churn_score  cltv                               churn_reason
0            1           86  3239               Competitor made better offer
1            1           67  2701                                      Moved
2            1           86  5372                                      Moved
3            1           84  5003                                      Moved
4            1           89  5340              Competitor had better devices
5            1           78  5925  Competitor offered higher download speeds
6            1          100  5433               Competitor offered more data
7            1           92  4832               Competitor made better offer
8            1           77  5789              Competitor had better devices
9            1           97  2915              Competitor had better devices

Verificar ids duplicados:

In [21]:
query_duplicados_id = "SELECT costumer_id, COUNT(*) FROM staging.costumers GROUP BY costumer_id HAVING(COUNT(*)) > 1;"

df = pd.read_sql(query_duplicados_id, engine)

print(df)

Empty DataFrame
Columns: [costumer_id, count]
Index: []

Verificar datos duplicados:

In [23]:
query_datos_duplicados = "SELECT *, COUNT(*) FROM staging.costumers GROUP BY costumer_id HAVING(COUNT(*)) > 1"

df = pd.read_sql(query_datos_duplicados, engine)

print(df)

Empty DataFrame
Columns: [costumer_id, count_costumer, country, state_costumer, city, zip_code, lat_long, latitude, longitude, gender, senior_citizen, patner, dependents, tenure_months, phone_service, multiple_lines, internet_service, online_security, online_backup, device_protection, tech_support, streaming_tv, streaming_movies, contract, paperless_billing, payment_method, monthly_charge, total_charges, churn_label, churn_value, churn_score, cltv, churn_reason, count]
Index: []

Buscar datos nulos:

In [30]:
query_datos_null = "SELECT " \
                    "COUNT(*) FILTER (WHERE contract IS NULL) AS null_contract, " \
                    "COUNT(*) FILTER (WHERE total_charges IS NULL) AS null_total_charges, " \
                    "COUNT(*) FILTER (WHERE churn_label IS NULL) AS null_churn_value, " \
                    "COUNT(*) FILTER (WHERE churn_score IS NULL) AS null_churn_score, " \
                    "COUNT(*) FILTER (WHERE cltv IS NULL) AS cltv " \
                    "FROM staging.costumers;"


df = pd.read_sql(query_datos_null, engine)

print(df)

   null_contract  null_total_charges  null_churn_value  null_churn_score  cltv
0              0                  11                 0                 0     0

In [37]:
query_churn_nulos = "SELECT total_charges FROM staging.costumers"  # WHERE total_charges IS NULL;"

df = pd.read_sql(query_churn_nulos, engine)

print(df)

      total_charges
0            108.15
1            151.65
2            820.50
3           3046.05
4           5036.30
...             ...
7038        1419.40
7039        1990.50
7040        7362.90
7041         346.45
7042        6844.50

[7043 rows x 1 columns]

# Remplazar valores nulos

Utilizamos percentiles al 90%, es decir que el 90% de los datos estan por debajo de dicho percentil, lo cual nos da una perspectiva mas objetiva de los datos
sin la necesidad de usar una media que puede ser sesgada por los valores atipicos.

In [43]:
query_churn_nulos = "SELECT PERCENTILE_CONT(0.9) WITHIN GROUP(ORDER BY total_charges) FROM staging.costumers"  # WHERE total_charges IS NULL;"

df = pd.read_sql(query_churn_nulos, engine)

print(df)

   percentile_cont
0          5976.64

In [47]:
from sqlalchemy import text


   
query_update = text(
    """ UPDATE staging.costumers 
        SET total_charges= ( SELECT PERCENTILE_CONT(0.9) WITHIN GROUP(ORDER BY total_charges)
        FROM staging.costumers ) 
        WHERE total_charges IS NULL
    """
        )

with engine.begin() as conn:
    conn.execute(query_update)

In [49]:
query_datos_null = "SELECT " \
                    "COUNT(*) FILTER (WHERE contract IS NULL) AS null_contract, " \
                    "COUNT(*) FILTER (WHERE total_charges IS NULL) AS null_total_charges, " \
                    "COUNT(*) FILTER (WHERE churn_label IS NULL) AS null_churn_value, " \
                    "COUNT(*) FILTER (WHERE churn_score IS NULL) AS null_churn_score, " \
                    "COUNT(*) FILTER (WHERE cltv IS NULL) AS cltv " \
                    "FROM staging.costumers;"


df = pd.read_sql(query_datos_null, engine)

print(df)

   null_contract  null_total_charges  null_churn_value  null_churn_score  cltv
0              0                   0                 0                 0     0